modLoader="javafml"
loaderVersion="[64,)"
license="LGPL-3.0-only"

[[mods]]
modId="opacui"
version="${version}"
displayName="OPAC UI"
authors="mervyn"
description='''
A client-side GUI addon for Open Parties and Claims, providing a full party management screen.
'''

[[dependencies.opacui]]
    modId="forge"
    mandatory=true
    versionRange="[64.0.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opacui]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.2,26.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opacui]]
    modId="openpartiesandclaims"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="CLIENT"
