modLoader="javafml"
loaderVersion="[65,)"
license="LGPL-3.0-only"

[[mods]]
modId="opacui"
version="${version}"
displayName="OPAC UI"
authors="mervyn"
description='''
A client-side GUI addon for Open Parties and Claims, providing a full party management screen.
'''

[[dependencies.opacui]]
    modId="forge"
    mandatory=true
    versionRange="[65.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opacui]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.2,26.3.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opacui]]
    modId="openpartiesandclaims"
    mandatory=true
    versionRange="*"
    ordering="AFTER"
    side="CLIENT"
