# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
loader_version=0.16.5
loom_version=1.7-SNAPSHOT


# Forge & NeoForge Properties
forge_version=1.21.1-52.0.2
neoforge_version=21.1.65

# Mod Properties
mod_version=1.0.1
maven_group=mervyn
enabled_platforms=fabric,forge,neoforge


# Dependencies
fabric_api_version=0.105.0+1.21.1
cloth_config_fabric=5729125
cloth_config_forge=5729126
cloth_config_neoforge=5729127
opac_fabric=8507164
opac_forge=8507161
opac_neoforge=8507166
forgeconfigapiport_forge=7213610

