plugins {
	id 'architectury-plugin'
	id 'dev.architectury.loom'
	id 'com.github.johnrengelman.shadow'
}

architectury {
	platformSetupLoomIde()
	forge()
}

configurations {
	common
	shadowCommon
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentForge.extendsFrom common
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	forge "net.minecraftforge:forge:${project.forge_version}"

	// Dependencies provided by user for Forge
	modImplementation "curse.maven:cloth-config-348521:${project.cloth_config_forge}"
	modImplementation "curse.maven:open-parties-and-claims-636608:${project.opac_forge}"

	common(project(path: ":common", configuration: "namedElements")) { transitive false }
	shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive false }
}

loom {
	forge {
		mixinConfig "opacui.common.mixins.json"
	}
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("META-INF/mods.toml") {
		expand "version": version
	}
}

shadowJar {
	exclude "fabric.mod.json"
	configurations = [project.configurations.shadowCommon]
	archiveClassifier.set("dev-shadow")
}

remapJar {
	input.set shadowJar.archiveFile
	dependsOn shadowJar
	archiveClassifier.set(null)
}

jar {
	archiveClassifier.set("dev")
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}
