plugins {
	id 'idea'
	id 'net.neoforged.gradle.userdev' version '7.1.22'
}

java.withSourcesJar()

runs {
	configureEach {
		modSource project.sourceSets.main
	}
	client {
		argument '--username=Dev'
	}
	server {
		argument '--nogui'
	}
}

dependencies {
	implementation "net.neoforged:neoforge:${neoforge_version}"
	compileOnly project(":common")

	// Dependencies for NeoForge
	implementation "curse.maven:open-parties-and-claims-636608:${project.opac_neoforge}"
}

// NeoGradle compiles the game, but we don't want to add our common code to the game's code
// (or to compileTestJava, which has no real test sources of its own).
Spec<Task> notNeoTask = { Task it -> !it.name.startsWith("neo") && !it.name.contains("Test") } as Spec<Task>

tasks.withType(JavaCompile).matching(notNeoTask).configureEach {
	source(project(":common").sourceSets.main.allSource)
}

tasks.withType(ProcessResources).matching(notNeoTask).configureEach {
	from project(":common").sourceSets.main.resources

	def version = project.version
	inputs.property "version", version

	filesMatching("META-INF/neoforge.mods.toml") {
		expand "version": version
	}
}

tasks.named("sourcesJar", Jar) {
	from(project(":common").sourceSets.main.allSource)
}
