plugins {
	id 'architectury-plugin'
	id 'dev.architectury.loom'
	id 'com.github.johnrengelman.shadow'
}

architectury {
	platformSetupLoomIde()
	neoForge()
}

configurations {
	common
	shadowCommon
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentNeoForge.extendsFrom common
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	neoForge "net.neoforged:neoforge:${project.neoforge_version}"

	// Dependencies for NeoForge
	modImplementation "curse.maven:cloth-config-348521:${project.cloth_config_neoforge}"
	modImplementation "curse.maven:open-parties-and-claims-636608:${project.opac_neoforge}"

	common(project(path: ":common", configuration: "namedElements")) { transitive false }
	shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive false }
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("META-INF/neoforge.mods.toml") {
		expand "version": version
	}
}

shadowJar {
	exclude "fabric.mod.json"
	configurations = [project.configurations.shadowCommon]
	archiveClassifier.set("dev-shadow")
}

remapJar {
	input.set shadowJar.archiveFile
	dependsOn shadowJar
	archiveClassifier.set(null)
}

jar {
	archiveClassifier.set("dev")
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
